"""
ModuleEvent — Events generated by site modules (jobs, shop, forms, etc.)

These are reported by WordPress plugins/webhooks and feed into the unified timeline.
Examples:
- Job application submitted
- WooCommerce order placed
- Giftcard purchased
- FluentForm submission
- Contact form filled
"""
import enum
import uuid
from datetime import datetime

from sqlalchemy import String, Integer, Text, Enum, DateTime, ForeignKey, func
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class ModuleEventType(str, enum.Enum):
    # Jobs
    job_application = "job_application"
    job_published = "job_published"
    job_expired = "job_expired"

    # Shop / WooCommerce
    order_placed = "order_placed"
    order_completed = "order_completed"
    order_refunded = "order_refunded"
    product_published = "product_published"

    # Giftcard
    giftcard_purchased = "giftcard_purchased"
    giftcard_redeemed = "giftcard_redeemed"

    # Forms
    form_submitted = "form_submitted"

    # Mail
    mail_received = "mail_received"
    mail_bounced = "mail_bounced"

    # Booking
    booking_created = "booking_created"
    booking_cancelled = "booking_cancelled"

    # Generic
    custom = "custom"


class ModuleEvent(Base):
    """An event from a site module, reported via webhook."""
    __tablename__ = "module_events"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False, index=True)
    module_type: Mapped[str] = mapped_column(String(50), nullable=False, index=True)  # jobs, shop, giftcard, forms, etc.
    event_type: Mapped[ModuleEventType] = mapped_column(Enum(ModuleEventType), nullable=False, index=True)

    title: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    severity: Mapped[str] = mapped_column(String(20), nullable=False, default="info")  # info, success, warning, error

    # Flexible data payload
    data: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    # e.g. for job_application: {"applicant_name": "Jan", "job_title": "Chef", "email": "jan@..."}
    # e.g. for order_placed: {"order_id": 1234, "total": 49.99, "items": 3}
    # e.g. for form_submitted: {"form_name": "Contact", "fields": {"name": "...", "email": "..."}}

    source_url: Mapped[str | None] = mapped_column(String(500), nullable=True)  # URL where event originated
    source_ip: Mapped[str | None] = mapped_column(String(45), nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
